"""add timetable

Revision ID: a3f57d718667
Revises: 264d0b737d17
Create Date: 2025-03-20 01:55:16.007641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3f57d718667"
down_revision: Union[str, None] = "264d0b737d17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hmm_hero_used_time_table",
        sa.Column("hero_id", sa.Uuid(), nullable=False),
        sa.Column("expedition_id", sa.Uuid(), nullable=False),
        sa.Column("date_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expedition_id"],
            ["hmm_expedition_template.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["hero_id"], ["hmm_hero.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hmm_hero_used_time_table_date_end"),
        "hmm_hero_used_time_table",
        ["date_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hmm_hero_used_time_table_date_start"),
        "hmm_hero_used_time_table",
        ["date_start"],
        unique=False,
    )
    op.alter_column(
        "hmm_expedition_template",
        "w_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "m_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "s_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "total_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_hero",
        "mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "w_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "m_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "s_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hmm_typical_sub_task",
        "s_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "m_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "w_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_hero",
        "mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_expedition_template",
        "total_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "s_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "m_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "w_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.drop_index(
        op.f("ix_hmm_hero_used_time_table_date_start"),
        table_name="hmm_hero_used_time_table",
    )
    op.drop_index(
        op.f("ix_hmm_hero_used_time_table_date_end"),
        table_name="hmm_hero_used_time_table",
    )
    op.drop_table("hmm_hero_used_time_table")
    # ### end Alembic commands ###
