"""add admin

Revision ID: ccfdc6b629e9
Revises: 0480aefc03c9
Create Date: 2025-03-19 10:50:38.731132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from hmm.models.auth import User
from hmm.schemas.auth import UserCreate

# revision identifiers, used by Alembic.
revision: str = "ccfdc6b629e9"
down_revision: Union[str, None] = "0480aefc03c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    user = UserCreate(username="admin", password="admin", is_super=True)
    stmt = sa.insert(User).values(
        user.model_dump(exclude_unset=True, exclude_none=True)
    )
    op.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    stmt = sa.delete(User).where(User.username == "admin")
    op.execute(stmt)
    # ### end Alembic commands ###
