"""add expedition details

Revision ID: eaaa6bacc06c
Revises: a3f57d718667
Create Date: 2025-03-20 10:33:30.431423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eaaa6bacc06c"
down_revision: Union[str, None] = "a3f57d718667"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hmm_expedition_template",
        sa.Column(
            "mean_exp_lvl",
            sa.Float(precision=2),
            server_default="1",
            nullable=False,
        ),
    )
    op.alter_column(
        "hmm_expedition_template",
        "w_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "m_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "s_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "total_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_hero",
        "mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "w_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "m_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "s_mana",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hmm_typical_sub_task",
        "s_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "m_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_typical_sub_task",
        "w_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_hero",
        "mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "hmm_expedition_template",
        "total_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "s_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "m_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.alter_column(
        "hmm_expedition_template",
        "w_mana",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::real"),
    )
    op.drop_column("hmm_expedition_template", "mean_exp_lvl")
    # ### end Alembic commands ###
