"""add models

Revision ID: eeb44c191c6e
Revises: ccfdc6b629e9
Create Date: 2025-03-19 14:02:12.493621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eeb44c191c6e"
down_revision: Union[str, None] = "ccfdc6b629e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hmm_expedition_template",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hmm_hero",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("hero_class", sa.SmallInteger(), nullable=False),
        sa.Column("hero_lvl", sa.SmallInteger(), nullable=False),
        sa.Column("mana", sa.Float(precision=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hmm_hero_hero_class"),
        "hmm_hero",
        ["hero_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hmm_hero_hero_lvl"), "hmm_hero", ["hero_lvl"], unique=False
    )
    op.create_table(
        "hmm_task_group",
        sa.Column(
            "name", sa.String(length=256), server_default="", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hmm_typical_sub_task",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("task_type", sa.SmallInteger(), nullable=False),
        sa.Column("task_lvl", sa.SmallInteger(), nullable=False),
        sa.Column("w_mana", sa.Float(precision=2), nullable=False),
        sa.Column("m_mana", sa.Float(precision=2), nullable=False),
        sa.Column("s_mana", sa.Float(precision=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hmm_typical_sub_task_task_lvl"),
        "hmm_typical_sub_task",
        ["task_lvl"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hmm_typical_sub_task_task_type"),
        "hmm_typical_sub_task",
        ["task_type"],
        unique=False,
    )
    op.create_table(
        "hmm_chronicles",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "date_start",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_end",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expedition_template_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expedition_template_id"],
            ["hmm_expedition_template.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hmm_chronicles_expedition_template_id"),
        "hmm_chronicles",
        ["expedition_template_id"],
        unique=False,
    )
    op.create_table(
        "hmm_task2_expedition",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("expedition_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expedition_id"],
            ["hmm_expedition_template.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["hmm_task_group.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "expedition_id"),
    )
    op.create_table(
        "hmm_task2_group",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("typical_task", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["hmm_task_group.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["typical_task"], ["hmm_typical_sub_task.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "typical_task"),
    )
    op.create_table(
        "hmm_heroes2_chronicles",
        sa.Column("hero_id", sa.Uuid(), nullable=False),
        sa.Column("chronicle_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chronicle_id"], ["hmm_chronicles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["hero_id"], ["hmm_hero.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("hero_id", "chronicle_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hmm_heroes2_chronicles")
    op.drop_table("hmm_task2_group")
    op.drop_table("hmm_task2_expedition")
    op.drop_index(
        op.f("ix_hmm_chronicles_expedition_template_id"),
        table_name="hmm_chronicles",
    )
    op.drop_table("hmm_chronicles")
    op.drop_index(
        op.f("ix_hmm_typical_sub_task_task_type"),
        table_name="hmm_typical_sub_task",
    )
    op.drop_index(
        op.f("ix_hmm_typical_sub_task_task_lvl"),
        table_name="hmm_typical_sub_task",
    )
    op.drop_table("hmm_typical_sub_task")
    op.drop_table("hmm_task_group")
    op.drop_index(op.f("ix_hmm_hero_hero_lvl"), table_name="hmm_hero")
    op.drop_index(op.f("ix_hmm_hero_hero_class"), table_name="hmm_hero")
    op.drop_table("hmm_hero")
    op.drop_table("hmm_expedition_template")
    # ### end Alembic commands ###
